@startuml
!theme plain
skinparam rectangle {
    BackgroundColor White
    BorderColor Black
}

actor "Aluno" as aluno
rectangle ": InterfaceWeb" as ui
rectangle ": AgendamentoController" as ctrl
rectangle ": TurmaService" as srv
rectangle ": TurmaRepository" as repoTurma
rectangle ": AgendamentoRepository" as repoAgend

aluno -right-> ui : 1: clicaConfirmarAgendamento()
ui -right-> ctrl : 1.1: POST /api/agendamentos
ctrl -down-> srv : 1.1.1: realizarAgendamento(idTurma, idAluno)
srv -left-> repoTurma : 1.1.1.1: findById(idTurma)\n1.1.1.3: decrementarVaga(idTurma)
srv -right-> repoAgend : 1.1.1.2: save(novoAgendamento)
@enduml
